# Docs for the Azure Web Apps Deploy action: https://github.com/azure/functions-action
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js project to Azure Function App - foxy-cpq

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: './api'
  NODE_VERSION: '20.x'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v4

      - name: Setup Node ${{ env.NODE_VERSION }} Environment
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: 'Resolve Project Dependencies Using Npm'
        shell: bash
        run: |
          pushd './api'
          npm install
          npm run build:ci
          npm run test --if-present
          popd

      - name: 'Display build output'
        run: |
          echo "Contents of api/dist directory:"
          ls -R ./api/dist

      - name: Zip artifact for deployment
        run: |
          cd ./api
          zip -r ../release.zip .

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: |
          mkdir api
          unzip release.zip -d api
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_6A899B372ABB40BE9456CA05200CC88F }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_0DB27508A8364B2FAF9AEE18EEB14EE7 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_06DF1C6253D14A74AE27C640FC46EAC5 }}

      - name: 'Stop Azure Function App'
        uses: Azure/cli@v1
        with:
          inlineScript: |
            az functionapp stop --name foxy-cpq --resource-group cpq

      - name: 'Run Azure Functions Action'
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: 'foxy-cpq'
          slot-name: 'Production'
          package: 'api'
          scm-do-build-during-deployment: true
          enable-oryx-build: true

      - name: 'Start Azure Function App'
        uses: Azure/cli@v1
        with:
          inlineScript: |
            az functionapp start --name foxy-cpq --resource-group cpq
