# Docs for the Azure Web Apps Deploy action: https://github.com/azure/functions-action
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js project to Azure Function App - foxy-cpq

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: './api'
  NODE_VERSION: '20.x'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v4

      - name: Setup Node ${{ env.NODE_VERSION }} Environment
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: 'Resolve Project Dependencies Using Npm'
        shell: bash
        run: |
          pushd './api'
          npm install
          npm run build:ci
          npm run test --if-present
          popd

      - name: 'Verify Build Output'
        shell: bash
        run: |
          echo "Verifying dist folder structure..."
          ls -R ./api/dist
          echo "Checking for function registrations..."
          grep -r "app.http" ./api/dist || true

      # Create package file (zip) for deployment
      - name: Create package for deployment
        run: |
          cd ./api
          zip -r ../package.zip . -x "node_modules/*"
          cd ..
          echo "Created deployment package"
          ls -lh package.zip

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: package.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_6A899B372ABB40BE9456CA05200CC88F }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_0DB27508A8364B2FAF9AEE18EEB14EE7 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_06DF1C6253D14A74AE27C640FC46EAC5 }}

      # Configure app settings before deployment
      - name: 'Configure Function App Settings'
        uses: Azure/cli@v1
        with:
          inlineScript: |
            echo "Configuring app settings..."
            az functionapp config appsettings set --name foxy-cpq --resource-group cpq --settings WEBSITE_RUN_FROM_PACKAGE=1
            az functionapp config appsettings set --name foxy-cpq --resource-group cpq --settings FUNCTIONS_WORKER_RUNTIME=node
            az functionapp config appsettings set --name foxy-cpq --resource-group cpq --settings FUNCTIONS_EXTENSION_VERSION=~4
            az functionapp config appsettings set --name foxy-cpq --resource-group cpq --settings SCM_DO_BUILD_DURING_DEPLOYMENT=true
            echo "Configured app settings"

      # Stop the function app before deployment
      - name: 'Stop Function App'
        uses: Azure/cli@v1
        with:
          inlineScript: |
            echo "Stopping function app..."
            az functionapp stop --name foxy-cpq --resource-group cpq
            echo "Waiting for app to stop..."
            sleep 10

      # Deploy the package
      - name: 'Deploy Function App Package'
        uses: Azure/cli@v1
        with:
          inlineScript: |
            echo "Deploying package..."
            az functionapp deployment source config-zip -g cpq -n foxy-cpq --src package.zip
            echo "Deployment completed"

      # Start the function app after deployment
      - name: 'Start Function App'
        uses: Azure/cli@v1
        with:
          inlineScript: |
            echo "Starting function app..."
            az functionapp start --name foxy-cpq --resource-group cpq
            echo "Waiting for app to start..."
            sleep 30

      # Verify deployment
      - name: 'Verify Deployment'
        uses: Azure/cli@v1
        with:
          inlineScript: |
            echo "Checking function app status..."
            az functionapp list -g cpq --query "[?name=='foxy-cpq'].{Name:name, State:state}" -o table
            echo "Listing functions..."
            az functionapp function list -g cpq -n foxy-cpq -o table
            echo "Testing function endpoint..."
            curl -v "https://foxy-cpq.azurewebsites.net/api/test" || true
