name: Build and deploy Node.js project to Azure Function App - foxyrita

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: './api/dist/functions' # Ensure this points correctly
  NODE_VERSION: '18.x' # Node version

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v4

      - name: Setup Node ${{ env.NODE_VERSION }} Environment
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: 'Use specific npm version'
        run: |
          npm install -g npm@8.19.2

      - name: 'Resolve Project Dependencies Using Npm'
        shell: bash
        run: |
          pushd './api'
          npm install
          npm run build
          npm run test --if-present
          popd

      - name: 'Display api directory contents'
        run: |
          echo "Contents of api directory:"
          ls -R ./api

      - name: Zip artifact for deployment
        run: |
          cd ./api/dist/functions
          zip -r ../../../release.zip ./*

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    permissions:
      id-token: write # Required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_08C2026672584E2E85B2D5736BAEC368 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_90389E60FEE1480888E1680FD5E65FB9 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_62F4CFC44DC141859B311C4553017B99 }}

      - name: 'Run Azure Functions Action'
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: 'foxyrita'
          slot-name: 'Production'
          package: release.zip